# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    command_handler:
        class: AppDomain\CommandHandler
        arguments:
            - "@doctrine.orm.events_entity_manager"
    paper_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Paper
    paper_event_handler:
        class: AppBundle\PaperHandler
        arguments:
            - "@paper_repository"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: doctrine.orm.entity_listener, entity_manager: events, entity: AppDomain\Event\PaperEvent, event: postPersist }